[ko]
  title = "쪼식이 블로그"
  languageName = "한국어"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/ko"
  
[en]
  title = "机器学习算法与Python实战"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content"

  [zh]
  title = "机器学习算法与Python实战"
  languageName = "Chinese"
  weight = 2
  languagedir = "ltr"
  contentdir = "content"