[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 1

[[main]]
  identifier = "python"
  name = "Python"
  url = "python"
  weight = 2

[[main]]
  identifier = "资料"
  name = "资料"
  url = "books"
  weight = 3

[[main]]
  identifier = "机器学习"
  name = "机器学习"
  url = "ml"
  weight = 4
    
[[main]]
  parent = "ml"
  name = "教程"
  url = "ml/course"

[[main]]
  parent = "ml"
  name = "实战"
  url = "ml/codes"

[[main]]
  identifier = "AIGC"
  name = "AIGC"
  url = "aigc"
  weight = 5

[[main]]
  identifier = "数学基础"
  name = "数学基础"
  url = "math"
  weight = 6

[[main]]
  identifier = "闲聊"
  name = "闲聊"
  url = "talks"
  weight = 7